# Generated by Django 6.1 on 2026-08-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(db_column='Id_Pago', primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(db_column='Tipo_Pago', max_length=20)),
                ('mes_ano', models.DateTimeField(db_column='Mes_Año')),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField(db_column='Fecha_Vencimiento')),
                ('fecha_pago', models.DateField(blank=True, db_column='Fecha_Pago', null=True)),
                ('metodo_pago', models.CharField(blank=True, db_column='Metodo_Pago', max_length=30, null=True)),
                ('comprobante_url', models.CharField(blank=True, db_column='Comprobante_Url', max_length=255, null=True)),
                ('estado', models.CharField(db_column='Estado', default='Pendiente', max_length=20)),
                ('id_reserva_fk', models.ForeignKey(blank=True, db_column='Id_Reserva_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.reservas')),
                ('id_residente_fk', models.ForeignKey(blank=True, db_column='Id_Residente_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='residentes.residentes')),
            ],
            options={
                'db_table': 'pagos',
                'managed': True,
            },
        ),
    ]
