# Generated by Django 6.1 on 2026-08-29 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id_visitante', models.AutoField(db_column='Id_Visitante', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=100, null=True)),
                ('tipo_documento', models.CharField(blank=True, db_column='Tipo_Documento', max_length=20, null=True)),
                ('num_documento', models.CharField(blank=True, db_column='Num_Documento', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('motivo', models.CharField(blank=True, db_column='Motivo', max_length=255, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='Fecha_Ingreso', null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, db_column='Fecha_Salida', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=20, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, db_column='Autorizado_Por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_residente_fk', models.ForeignKey(blank=True, db_column='Id_Residente_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='residentes.residentes')),
            ],
            options={
                'db_table': 'visitantes',
                'managed': True,
            },
        ),
    ]
