# Generated by Django 6.1 on 2026-08-29 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(db_column='Id_Vehiculo', primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, db_column='Placa', max_length=10, null=True)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, db_column='Modelo', max_length=50, null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=30, null=True)),
                ('tipo_vehiculo', models.CharField(blank=True, db_column='Tipo_Vehiculo', max_length=20, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=20, null=True)),
                ('id_residente_fk', models.ForeignKey(blank=True, db_column='Id_Residente_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='residentes.residentes')),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': True,
            },
        ),
    ]
