# Generated by Django 6.1 on 2026-08-29 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDano',
            fields=[
                ('id_reportes', models.AutoField(db_column='Id_Reportes', primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=50, null=True)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('torre', models.CharField(blank=True, db_column='Torre', max_length=10, null=True)),
                ('piso', models.IntegerField(blank=True, db_column='Piso', null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, db_column='Fecha_Reporte')),
                ('estado', models.CharField(db_column='Estado', default='Abierto', max_length=20)),
                ('asignado_a_fk', models.IntegerField(blank=True, db_column='Asignado_a_FK', null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, db_column='Fecha_Resolucion', null=True)),
                ('id_residente_fk', models.ForeignKey(db_column='Id_Residente_FK', on_delete=django.db.models.deletion.DO_NOTHING, to='residentes.residentes')),
            ],
            options={
                'db_table': 'reportes',
                'managed': True,
            },
        ),
    ]
