# Generated by Django 6.1 on 2026-08-29 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id_unidad', models.AutoField(db_column='Id_Unidad', primary_key=True, serialize=False)),
                ('torre', models.CharField(blank=True, db_column='Torre', max_length=10, null=True)),
                ('apto', models.CharField(blank=True, db_column='Apto', max_length=10, null=True)),
                ('piso', models.IntegerField(blank=True, db_column='Piso', null=True)),
                ('area', models.DecimalField(blank=True, db_column='Area', decimal_places=2, max_digits=8, null=True)),
                ('id_residente_fk', models.IntegerField(blank=True, db_column='Id_Residente_FK', null=True)),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'unidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Residentes',
            fields=[
                ('id_residente', models.AutoField(db_column='Id_Residente', primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(blank=True, db_column='Tipo_Documento', max_length=100, null=True)),
                ('num_documento', models.CharField(blank=True, db_column='Num_Documento', max_length=100, null=True)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, db_column='Fecha_Registro', null=True)),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
                ('id_unidad_fk', models.ForeignKey(blank=True, db_column='Id_Unidad_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='residentes.unidades')),
            ],
            options={
                'db_table': 'residentes',
                'managed': True,
            },
        ),
    ]
