# Generated by Django 6.1 on 2026-08-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonasComunes',
            fields=[
                ('id_zona', models.AutoField(db_column='Id_Zona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=250, null=True)),
                ('capacidad', models.IntegerField(blank=True, db_column='Capacidad', null=True)),
                ('reglas', models.TextField(blank=True, db_column='Reglas', null=True)),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'zonas_comunes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reservas', models.AutoField(db_column='Id_Reservas', primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(blank=True, db_column='Fecha_Reserva', null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, db_column='Fecha_Inicio', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, db_column='Fecha_Fin', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('id_unidad_fk', models.ForeignKey(blank=True, db_column='Id_Unidad_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='residentes.unidades')),
                ('id_zona_fk', models.ForeignKey(blank=True, db_column='Id_Zona_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.zonascomunes')),
            ],
            options={
                'db_table': 'reservas',
                'managed': True,
            },
        ),
    ]
